// =============================================
// Rekaz - IFRS Default Chart of Accounts
// =============================================
const DEFAULT_COA = [
  // 1xxx - Assets
  { code: '1000', nameAr: 'الأصول', nameEn: 'Assets', type: 'assets', nature: 'debit', parentCode: null, level: 0, isHeader: true },
  { code: '1100', nameAr: 'الأصول المتداولة', nameEn: 'Current Assets', type: 'assets', nature: 'debit', parentCode: '1000', level: 1, isHeader: true },
  { code: '1110', nameAr: 'النقد وما يعادله', nameEn: 'Cash & Cash Equivalents', type: 'assets', nature: 'debit', parentCode: '1100', level: 2, isHeader: true },
  { code: '1111', nameAr: 'الصندوق', nameEn: 'Cash on Hand', type: 'assets', nature: 'debit', parentCode: '1110', level: 3, isHeader: false },
  { code: '1112', nameAr: 'البنك', nameEn: 'Bank Account', type: 'assets', nature: 'debit', parentCode: '1110', level: 3, isHeader: false },
  { code: '1113', nameAr: 'ودائع قصيرة الأجل', nameEn: 'Short-term Deposits', type: 'assets', nature: 'debit', parentCode: '1110', level: 3, isHeader: false },
  { code: '1120', nameAr: 'المدينون', nameEn: 'Accounts Receivable', type: 'assets', nature: 'debit', parentCode: '1100', level: 2, isHeader: true },
  { code: '1121', nameAr: 'العملاء', nameEn: 'Trade Receivables', type: 'assets', nature: 'debit', parentCode: '1120', level: 3, isHeader: false },
  { code: '1122', nameAr: 'أوراق القبض', nameEn: 'Notes Receivable', type: 'assets', nature: 'debit', parentCode: '1120', level: 3, isHeader: false },
  { code: '1123', nameAr: 'مخصص الديون المشكوك فيها', nameEn: 'Allowance for Doubtful Debts', type: 'assets', nature: 'credit', parentCode: '1120', level: 3, isHeader: false },
  { code: '1130', nameAr: 'المخزون', nameEn: 'Inventory', type: 'assets', nature: 'debit', parentCode: '1100', level: 2, isHeader: true },
  { code: '1131', nameAr: 'بضاعة جاهزة', nameEn: 'Finished Goods', type: 'assets', nature: 'debit', parentCode: '1130', level: 3, isHeader: false },
  { code: '1132', nameAr: 'مواد خام', nameEn: 'Raw Materials', type: 'assets', nature: 'debit', parentCode: '1130', level: 3, isHeader: false },
  { code: '1133', nameAr: 'بضاعة تحت التصنيع', nameEn: 'Work in Progress', type: 'assets', nature: 'debit', parentCode: '1130', level: 3, isHeader: false },
  { code: '1140', nameAr: 'مصروفات مدفوعة مقدماً', nameEn: 'Prepaid Expenses', type: 'assets', nature: 'debit', parentCode: '1100', level: 2, isHeader: false },
  { code: '1150', nameAr: 'إيرادات مستحقة', nameEn: 'Accrued Revenue', type: 'assets', nature: 'debit', parentCode: '1100', level: 2, isHeader: false },

  { code: '1200', nameAr: 'الأصول غير المتداولة', nameEn: 'Non-Current Assets', type: 'assets', nature: 'debit', parentCode: '1000', level: 1, isHeader: true },
  { code: '1210', nameAr: 'الممتلكات والمعدات', nameEn: 'Property, Plant & Equipment', type: 'assets', nature: 'debit', parentCode: '1200', level: 2, isHeader: true },
  { code: '1211', nameAr: 'الأراضي', nameEn: 'Land', type: 'assets', nature: 'debit', parentCode: '1210', level: 3, isHeader: false },
  { code: '1212', nameAr: 'المباني', nameEn: 'Buildings', type: 'assets', nature: 'debit', parentCode: '1210', level: 3, isHeader: false },
  { code: '1213', nameAr: 'الأثاث والتجهيزات', nameEn: 'Furniture & Fixtures', type: 'assets', nature: 'debit', parentCode: '1210', level: 3, isHeader: false },
  { code: '1214', nameAr: 'المعدات والآلات', nameEn: 'Machinery & Equipment', type: 'assets', nature: 'debit', parentCode: '1210', level: 3, isHeader: false },
  { code: '1215', nameAr: 'السيارات ووسائل النقل', nameEn: 'Vehicles', type: 'assets', nature: 'debit', parentCode: '1210', level: 3, isHeader: false },
  { code: '1216', nameAr: 'أجهزة حاسب آلي', nameEn: 'Computer Equipment', type: 'assets', nature: 'debit', parentCode: '1210', level: 3, isHeader: false },
  { code: '1220', nameAr: 'مجمع الاستهلاك', nameEn: 'Accumulated Depreciation', type: 'assets', nature: 'credit', parentCode: '1200', level: 2, isHeader: true },
  { code: '1221', nameAr: 'مجمع استهلاك المباني', nameEn: 'Accum. Depr. - Buildings', type: 'assets', nature: 'credit', parentCode: '1220', level: 3, isHeader: false },
  { code: '1222', nameAr: 'مجمع استهلاك الأثاث', nameEn: 'Accum. Depr. - Furniture', type: 'assets', nature: 'credit', parentCode: '1220', level: 3, isHeader: false },
  { code: '1223', nameAr: 'مجمع استهلاك المعدات', nameEn: 'Accum. Depr. - Equipment', type: 'assets', nature: 'credit', parentCode: '1220', level: 3, isHeader: false },
  { code: '1224', nameAr: 'مجمع استهلاك السيارات', nameEn: 'Accum. Depr. - Vehicles', type: 'assets', nature: 'credit', parentCode: '1220', level: 3, isHeader: false },
  { code: '1230', nameAr: 'أصول غير ملموسة', nameEn: 'Intangible Assets', type: 'assets', nature: 'debit', parentCode: '1200', level: 2, isHeader: true },
  { code: '1231', nameAr: 'الشهرة', nameEn: 'Goodwill', type: 'assets', nature: 'debit', parentCode: '1230', level: 3, isHeader: false },
  { code: '1232', nameAr: 'برامج وتراخيص', nameEn: 'Software & Licenses', type: 'assets', nature: 'debit', parentCode: '1230', level: 3, isHeader: false },
  { code: '1233', nameAr: 'علامات تجارية', nameEn: 'Trademarks', type: 'assets', nature: 'debit', parentCode: '1230', level: 3, isHeader: false },
  { code: '1240', nameAr: 'استثمارات طويلة الأجل', nameEn: 'Long-term Investments', type: 'assets', nature: 'debit', parentCode: '1200', level: 2, isHeader: false },

  // 2xxx - Liabilities
  { code: '2000', nameAr: 'الالتزامات', nameEn: 'Liabilities', type: 'liabilities', nature: 'credit', parentCode: null, level: 0, isHeader: true },
  { code: '2100', nameAr: 'الالتزامات المتداولة', nameEn: 'Current Liabilities', type: 'liabilities', nature: 'credit', parentCode: '2000', level: 1, isHeader: true },
  { code: '2110', nameAr: 'الدائنون', nameEn: 'Accounts Payable', type: 'liabilities', nature: 'credit', parentCode: '2100', level: 2, isHeader: true },
  { code: '2111', nameAr: 'الموردون', nameEn: 'Trade Payables', type: 'liabilities', nature: 'credit', parentCode: '2110', level: 3, isHeader: false },
  { code: '2112', nameAr: 'أوراق الدفع', nameEn: 'Notes Payable', type: 'liabilities', nature: 'credit', parentCode: '2110', level: 3, isHeader: false },
  { code: '2120', nameAr: 'مصروفات مستحقة', nameEn: 'Accrued Expenses', type: 'liabilities', nature: 'credit', parentCode: '2100', level: 2, isHeader: false },
  { code: '2130', nameAr: 'إيرادات مؤجلة', nameEn: 'Deferred Revenue', type: 'liabilities', nature: 'credit', parentCode: '2100', level: 2, isHeader: false },
  { code: '2140', nameAr: 'ضريبة القيمة المضافة', nameEn: 'VAT Payable', type: 'liabilities', nature: 'credit', parentCode: '2100', level: 2, isHeader: false },
  { code: '2150', nameAr: 'رواتب مستحقة', nameEn: 'Salaries Payable', type: 'liabilities', nature: 'credit', parentCode: '2100', level: 2, isHeader: false },
  { code: '2160', nameAr: 'قروض قصيرة الأجل', nameEn: 'Short-term Loans', type: 'liabilities', nature: 'credit', parentCode: '2100', level: 2, isHeader: false },
  { code: '2170', nameAr: 'الجزء المتداول من القروض الطويلة', nameEn: 'Current Portion of LT Debt', type: 'liabilities', nature: 'credit', parentCode: '2100', level: 2, isHeader: false },

  { code: '2200', nameAr: 'الالتزامات غير المتداولة', nameEn: 'Non-Current Liabilities', type: 'liabilities', nature: 'credit', parentCode: '2000', level: 1, isHeader: true },
  { code: '2210', nameAr: 'قروض طويلة الأجل', nameEn: 'Long-term Loans', type: 'liabilities', nature: 'credit', parentCode: '2200', level: 2, isHeader: false },
  { code: '2220', nameAr: 'مخصص مكافأة نهاية الخدمة', nameEn: 'End of Service Benefits', type: 'liabilities', nature: 'credit', parentCode: '2200', level: 2, isHeader: false },
  { code: '2230', nameAr: 'التزامات إيجارية طويلة الأجل', nameEn: 'Long-term Lease Obligations', type: 'liabilities', nature: 'credit', parentCode: '2200', level: 2, isHeader: false },

  // 3xxx - Equity
  { code: '3000', nameAr: 'حقوق الملكية', nameEn: 'Equity', type: 'equity', nature: 'credit', parentCode: null, level: 0, isHeader: true },
  { code: '3100', nameAr: 'رأس المال', nameEn: 'Share Capital', type: 'equity', nature: 'credit', parentCode: '3000', level: 1, isHeader: false },
  { code: '3200', nameAr: 'علاوة إصدار', nameEn: 'Share Premium', type: 'equity', nature: 'credit', parentCode: '3000', level: 1, isHeader: false },
  { code: '3300', nameAr: 'الاحتياطي القانوني', nameEn: 'Legal Reserve', type: 'equity', nature: 'credit', parentCode: '3000', level: 1, isHeader: false },
  { code: '3400', nameAr: 'الاحتياطي العام', nameEn: 'General Reserve', type: 'equity', nature: 'credit', parentCode: '3000', level: 1, isHeader: false },
  { code: '3500', nameAr: 'أرباح مبقاة', nameEn: 'Retained Earnings', type: 'equity', nature: 'credit', parentCode: '3000', level: 1, isHeader: false },
  { code: '3600', nameAr: 'أرباح / خسائر العام', nameEn: 'Current Year Earnings', type: 'equity', nature: 'credit', parentCode: '3000', level: 1, isHeader: false },
  { code: '3700', nameAr: 'حساب جاري الشريك', nameEn: 'Owner\'s Drawing', type: 'equity', nature: 'debit', parentCode: '3000', level: 1, isHeader: false },

  // 4xxx - Revenue
  { code: '4000', nameAr: 'الإيرادات', nameEn: 'Revenue', type: 'revenue', nature: 'credit', parentCode: null, level: 0, isHeader: true },
  { code: '4100', nameAr: 'إيرادات المبيعات', nameEn: 'Sales Revenue', type: 'revenue', nature: 'credit', parentCode: '4000', level: 1, isHeader: true },
  { code: '4110', nameAr: 'مبيعات بضاعة', nameEn: 'Goods Sales', type: 'revenue', nature: 'credit', parentCode: '4100', level: 2, isHeader: false },
  { code: '4120', nameAr: 'مردودات المبيعات', nameEn: 'Sales Returns', type: 'revenue', nature: 'debit', parentCode: '4100', level: 2, isHeader: false },
  { code: '4130', nameAr: 'خصم مسموح به', nameEn: 'Sales Discounts', type: 'revenue', nature: 'debit', parentCode: '4100', level: 2, isHeader: false },
  { code: '4200', nameAr: 'إيرادات الخدمات', nameEn: 'Service Revenue', type: 'revenue', nature: 'credit', parentCode: '4000', level: 1, isHeader: false },
  { code: '4300', nameAr: 'إيرادات أخرى', nameEn: 'Other Revenue', type: 'revenue', nature: 'credit', parentCode: '4000', level: 1, isHeader: true },
  { code: '4310', nameAr: 'إيرادات فوائد', nameEn: 'Interest Income', type: 'revenue', nature: 'credit', parentCode: '4300', level: 2, isHeader: false },
  { code: '4320', nameAr: 'أرباح بيع أصول', nameEn: 'Gain on Asset Disposal', type: 'revenue', nature: 'credit', parentCode: '4300', level: 2, isHeader: false },
  { code: '4330', nameAr: 'إيرادات إيجار', nameEn: 'Rental Income', type: 'revenue', nature: 'credit', parentCode: '4300', level: 2, isHeader: false },
  { code: '4340', nameAr: 'إيرادات متنوعة', nameEn: 'Miscellaneous Income', type: 'revenue', nature: 'credit', parentCode: '4300', level: 2, isHeader: false },

  // 5xxx - Cost of Goods Sold
  { code: '5000', nameAr: 'تكلفة المبيعات', nameEn: 'Cost of Goods Sold', type: 'cogs', nature: 'debit', parentCode: null, level: 0, isHeader: true },
  { code: '5100', nameAr: 'تكلفة البضاعة المباعة', nameEn: 'Cost of Goods Sold', type: 'cogs', nature: 'debit', parentCode: '5000', level: 1, isHeader: false },
  { code: '5200', nameAr: 'مشتريات', nameEn: 'Purchases', type: 'cogs', nature: 'debit', parentCode: '5000', level: 1, isHeader: true },
  { code: '5210', nameAr: 'مشتريات بضاعة', nameEn: 'Goods Purchases', type: 'cogs', nature: 'debit', parentCode: '5200', level: 2, isHeader: false },
  { code: '5220', nameAr: 'مردودات المشتريات', nameEn: 'Purchase Returns', type: 'cogs', nature: 'credit', parentCode: '5200', level: 2, isHeader: false },
  { code: '5230', nameAr: 'خصم مكتسب', nameEn: 'Purchase Discounts', type: 'cogs', nature: 'credit', parentCode: '5200', level: 2, isHeader: false },
  { code: '5240', nameAr: 'مصاريف الشحن والنقل', nameEn: 'Freight & Shipping', type: 'cogs', nature: 'debit', parentCode: '5200', level: 2, isHeader: false },

  // 6xxx - Operating Expenses
  { code: '6000', nameAr: 'المصروفات التشغيلية', nameEn: 'Operating Expenses', type: 'expenses', nature: 'debit', parentCode: null, level: 0, isHeader: true },
  { code: '6100', nameAr: 'مصروفات إدارية وعمومية', nameEn: 'General & Admin Expenses', type: 'expenses', nature: 'debit', parentCode: '6000', level: 1, isHeader: true },
  { code: '6110', nameAr: 'الرواتب والأجور', nameEn: 'Salaries & Wages', type: 'expenses', nature: 'debit', parentCode: '6100', level: 2, isHeader: false },
  { code: '6120', nameAr: 'إيجار المكاتب', nameEn: 'Office Rent', type: 'expenses', nature: 'debit', parentCode: '6100', level: 2, isHeader: false },
  { code: '6130', nameAr: 'مصاريف كهرباء وماء', nameEn: 'Utilities', type: 'expenses', nature: 'debit', parentCode: '6100', level: 2, isHeader: false },
  { code: '6140', nameAr: 'مصاريف اتصالات وإنترنت', nameEn: 'Telecom & Internet', type: 'expenses', nature: 'debit', parentCode: '6100', level: 2, isHeader: false },
  { code: '6150', nameAr: 'مصاريف قرطاسية ومطبوعات', nameEn: 'Office Supplies', type: 'expenses', nature: 'debit', parentCode: '6100', level: 2, isHeader: false },
  { code: '6160', nameAr: 'مصاريف صيانة', nameEn: 'Maintenance & Repairs', type: 'expenses', nature: 'debit', parentCode: '6100', level: 2, isHeader: false },
  { code: '6170', nameAr: 'مصاريف تأمين', nameEn: 'Insurance Expense', type: 'expenses', nature: 'debit', parentCode: '6100', level: 2, isHeader: false },
  { code: '6180', nameAr: 'مصاريف استهلاك', nameEn: 'Depreciation Expense', type: 'expenses', nature: 'debit', parentCode: '6100', level: 2, isHeader: false },
  { code: '6190', nameAr: 'مصاريف إدارية أخرى', nameEn: 'Other Admin Expenses', type: 'expenses', nature: 'debit', parentCode: '6100', level: 2, isHeader: false },
  { code: '6200', nameAr: 'مصروفات بيعية وتسويقية', nameEn: 'Selling & Marketing Expenses', type: 'expenses', nature: 'debit', parentCode: '6000', level: 1, isHeader: true },
  { code: '6210', nameAr: 'مصاريف إعلان وتسويق', nameEn: 'Advertising & Marketing', type: 'expenses', nature: 'debit', parentCode: '6200', level: 2, isHeader: false },
  { code: '6220', nameAr: 'عمولات مبيعات', nameEn: 'Sales Commissions', type: 'expenses', nature: 'debit', parentCode: '6200', level: 2, isHeader: false },
  { code: '6230', nameAr: 'مصاريف سفر ونقل', nameEn: 'Travel & Transport', type: 'expenses', nature: 'debit', parentCode: '6200', level: 2, isHeader: false },
  { code: '6240', nameAr: 'مصاريف ضيافة', nameEn: 'Hospitality Expense', type: 'expenses', nature: 'debit', parentCode: '6200', level: 2, isHeader: false },

  // 7xxx - Other Expenses
  { code: '7000', nameAr: 'مصروفات أخرى', nameEn: 'Other Expenses', type: 'expenses', nature: 'debit', parentCode: null, level: 0, isHeader: true },
  { code: '7100', nameAr: 'مصاريف تمويلية', nameEn: 'Finance Costs', type: 'expenses', nature: 'debit', parentCode: '7000', level: 1, isHeader: true },
  { code: '7110', nameAr: 'مصروف فوائد', nameEn: 'Interest Expense', type: 'expenses', nature: 'debit', parentCode: '7100', level: 2, isHeader: false },
  { code: '7120', nameAr: 'رسوم بنكية', nameEn: 'Bank Charges', type: 'expenses', nature: 'debit', parentCode: '7100', level: 2, isHeader: false },
  { code: '7200', nameAr: 'خسائر بيع أصول', nameEn: 'Loss on Asset Disposal', type: 'expenses', nature: 'debit', parentCode: '7000', level: 1, isHeader: false },
  { code: '7300', nameAr: 'مصاريف متنوعة', nameEn: 'Miscellaneous Expenses', type: 'expenses', nature: 'debit', parentCode: '7000', level: 1, isHeader: false },
  { code: '7400', nameAr: 'ضريبة الدخل', nameEn: 'Income Tax Expense', type: 'expenses', nature: 'debit', parentCode: '7000', level: 1, isHeader: false },
  { code: '7500', nameAr: 'ديون معدومة', nameEn: 'Bad Debt Expense', type: 'expenses', nature: 'debit', parentCode: '7000', level: 1, isHeader: false }
];
